name: LIU

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download
      run: curl -Lo ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
    - name: Extract
      run: unzip ngrok.zip
    - name: Auth
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Install VNC Server
      run: |
        sudo apt-get update
        sudo apt-get install -y tightvncserver
        # يمكنك هنا إعداد VNC حسب تفضيلاتك، مثل تعيين دقة الشاشة
    - name: Configure User
      run: |
        sudo adduser --gecos "" --disabled-password suhaib
        echo "suhaib:123456" | sudo chpasswd
        sudo usermod -aG sudo suhaib
    - name: Configure Firewall
      run: sudo ufw allow 5901/tcp
    - name: Create Tunnel
      run: ./ngrok tcp 5901
