name: LIU

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Node.js
      run: sudo apt-get install -y nodejs npm

    - name: Install LocalTunnel
      run: npm install -g localtunnel

    - name: Install XRDP and XFCE
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp xfce4 xfce4-terminal
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Configure User
      run: |
        sudo adduser --gecos "" --disabled-password suhaib
        echo "suhaib:123456" | sudo chpasswd
        sudo usermod -aG sudo,ssl-cert suhaib

    - name: Configure XRDP
      run: |
        echo "xfce4-session" > ~/.xsession
        sudo systemctl restart xrdp

    - name: Configure Firewall
      run: sudo ufw allow 3389/tcp

    - name: Start LocalTunnel
      run: |
        lt --port 3389 --subdomain my-subdomain --print-requests > lt.log 2>&1 &
        sleep 5  # تأخير لإعطاء الوقت لبدء النفق

    - name: Get Tunnel Password
      run: |
        PASSWORD=$(curl -s https://loca.lt/mytunnelpassword)
        echo "Tunnel Password: $PASSWORD"
