name: CI Workflow

on: 
  push:
  workflow_dispatch:

jobs:
  setup:

    runs-on: ubuntu-latest

    steps:
    - name: Download ngrok
      run: curl -Lo ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
    
    - name: Extract ngrok
      run: unzip ngrok.zip
    
    - name: Authenticate ngrok
      run: ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Install XRDP
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
    
    - name: Create User
      run: |
        sudo adduser --gecos "" --disabled-password suhaib
        echo "suhaib:123456" | sudo chpasswd
        sudo usermod -aG sudo,ssl-cert suhaib
    
    - name: Configure Firewall
      run: sudo ufw allow 3389/tcp
    
    - name: Start ngrok Tunnel
      run: ./ngrok tcp 3389
