name: LIU

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download
      run: curl -Lo ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
    - name: Extract
      run: unzip ngrok.zip
    - name: Auth
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Install NoMachine
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget -O nomachine.deb https://download.nomachine.com/download/7.9/Linux/nomachine_7.9.2_1_amd64.deb
        sudo dpkg -i nomachine.deb
        sudo apt-get install -f  # لتثبيت أي تبعيات مفقودة
    - name: Configure User
      run: |
        sudo adduser --gecos "" --disabled-password suhaib
        echo "suhaib:123456" | sudo chpasswd
        sudo usermod -aG sudo suhaib
    - name: Configure Firewall
      run: sudo ufw allow 4000/tcp
    - name: Create Tunnel
      run: ./ngrok tcp 4000
