name: LIU

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install PageKite
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install pagekite

    - name: Install XRDP and XFCE
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp xfce4 xfce4-terminal
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Configure User
      run: |
        sudo adduser --gecos "" --disabled-password suhaib
        echo "suhaib:123456" | sudo chpasswd
        sudo usermod -aG sudo,ssl-cert suhaib

    - name: Configure XRDP
      run: |
        echo "xfce4-session" | sudo tee /home/suhaib/.xsession
        sudo chown suhaib:suhaib /home/suhaib/.xsession
        sudo systemctl restart xrdp

    - name: Configure Firewall
      run: sudo ufw allow 3389/tcp

    - name: Check XRDP Status
      run: sudo systemctl status xrdp
    
    - name: Start PageKite
      run: pagekite 3389 yoursubdomain.pagekite.me

    - name: Get Tunnel URL
      run: echo "Your tunnel URL is: https://yoursubdomain.pagekite.me"
