name: LIU

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install LocalTunnel
      run: npm install -g localtunnel

    - name: Install XRDP and XFCE
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp xfce4 xfce4-terminal
        sudo systemctl enable xrdp
        sudo systemctl start xrdp

    - name: Configure User
      run: |
        sudo adduser --gecos "" --disabled-password suhaib
        echo "suhaib:123456" | sudo chpasswd
        sudo usermod -aG sudo,ssl-cert suhaib

    - name: Configure XRDP
      run: |
        echo "xfce4-session" | sudo tee /home/suhaib/.xsession
        sudo chown suhaib:suhaib /home/suhaib/.xsession
        sudo systemctl restart xrdp

    - name: Configure Firewall
      run: sudo ufw allow 3389/tcp

    - name: Get and Print Tunnel Password Page
      run: |
        curl -s https://loca.lt/mytunnelpassword

    - name: Start LocalTunnel
      run: lt --port 3389
